.github/workflows/CI.yml
WeatherSensor.cpp
examples/BresserWeatherSensorBasic/BresserWeatherSensorBasic.ino
examples/BresserWeatherSensorCallback/BresserWeatherSensorCallback.ino
examples/BresserWeatherSensorDomoticz/BresserWeatherSensorDomoticz.ino
examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
examples/BresserWeatherSensorMQTTCustom/BresserWeatherSensorMQTTCustom.ino
examples/BresserWeatherSensorMQTTCustom/src/RainGauge.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensorCfg.h
examples/BresserWeatherSensorOptions/BresserWeatherSensorOptions.ino
examples/BresserWeatherSensorWaiting/BresserWeatherSensorWaiting.ino
package.json
src/WeatherSensor.cpp
src/WeatherSensorCfg.h
src/WeatherSensorCfg.h.template

Replace DEBUG_PRINT/DEBUG_PRINTLN by Arduino logging functions #23

Replace DEBUG_PRINT/DEBUG_PRINTLN by Arduino logging functions

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.h
src/WeatherSensor.cpp
src/WeatherSensor.h

see "decodeBresser5In1Payload() extracts rain-value from three digits instead of four digits" #22

decodeBresser5In1Payload(): added additional rain digit

---

src/WeatherSensor.cpp

Modified decodeBresser6In1Payload() to distinguish msg type based on 'flags' (msg[16])

Modified decodeBresser6In1Payload()

---

src/WeatherSensor.cpp
src/WeatherSensorCfg.h
src/WeatherSensorCfg.h.template

I have created a temporary variable for data whitening, so now it should work properly for 5-in-1 and 6-in-1. Please test these changes. It works properly for the 7-in-1 weather station.

Bug fix about data whitening for Bresser 7 in 1 decoder

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.h
library.properties
package.json
src/WeatherSensor.cpp

Changed decoding of rain value for 7-in-1 protocol according to https://github.com/merbanan/rtl_433/blob/master/src/devices/bresser_7in1.c

Fix 7in1 raingauge

---

.github/workflows/CI.yml
examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino

Configuration of WiFi access point and MQTT broker using WiFiManager

Added example BresserWeatherSensorMQTTWifiMgr

---

README.md
examples/BresserWeatherSensorBasic/BresserWeatherSensorBasic.ino
src/WeatherSensor.cpp
src/WeatherSensor.h

Integration of Pool / Spa Thermometer P/N 7009973

Feature pool thermometer

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
src/WeatherSensor.cpp

7-in-1, leakage and lightning decoders

Fixed polarity of startup flags

---

examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino

Check double reset only in case of power-on / hw reset

Fix double reset detect

---

examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
src/Lightning.cpp
src/Lightning.h
src/WeatherSensor.h

Added data storage via Preferences, modified history implementation

Feature lightning nvs

---

examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino

* Replaced SPIFFS by LittleFS
* Fixed formatting of LittleFS partition (initially or after erasing the Flash)

Fix wifimanager

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.h
src/WeatherSensor.cpp
src/WeatherSensor.h
src/WeatherSensorCfg.h

Required for BresserWeatherSensorLW

Added radioReset()

---

examples/BresserWeatherSensorBasic/BresserWeatherSensorBasic.ino
examples/BresserWeatherSensorCallback/BresserWeatherSensorCallback.ino
examples/BresserWeatherSensorDomoticz/BresserWeatherSensorDomoticz.ino
examples/BresserWeatherSensorM5Core2/BresserWeatherSensorM5Core2.ino
examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
examples/BresserWeatherSensorMQTTCustom/BresserWeatherSensorMQTTCustom.ino
examples/BresserWeatherSensorMQTTCustom/src/InitBoard.cpp
examples/BresserWeatherSensorMQTTCustom/src/InitBoard.h
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.h
examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino
examples/BresserWeatherSensorOptions/BresserWeatherSensorOptions.ino
examples/BresserWeatherSensorTest/BresserWeatherSensorTest.ino
examples/BresserWeatherSensorTestCfg/BresserWeatherSensorTestCfg.ino
examples/BresserWeatherSensorWaiting/BresserWeatherSensorWaiting.ino
src/InitBoard.cpp
src/InitBoard.h
src/WeatherSensor.cpp
src/WeatherSensor.h

Moved board specific initialization from library to InitBoard.h/.cpp, called from sketch

Refactored board initialization

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.h
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensorDecoders.cpp
library.properties
package.json
src/WeatherSensor.cpp
src/WeatherSensor.h
src/WeatherSensorDecoders.cpp

Added features required by https://github.com/matthias-bs/BresserWeatherSensorLW/pull/79

Feat scan sensors

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensorCfg.h
src/WeatherSensorCfg.h
src/WeatherSensorCfg.h.template

See https://github.com/matthias-bs/BresserWeatherSensorReceiver/issues/203#issuecomment-2508963910

Added Heltec Vision Master T190

---

BUILD.md
README.md
src/Lightning.cpp
src/WeatherSensor.cpp
src/WeatherSensor.h
src/WeatherSensorConfig.cpp
src/WeatherSensorDecoders.cpp
src/WeatherUtils.cpp
src/WeatherUtils.h

I don't mean to be overly nit-picky, but while trying to figure out how all this works in detail I stumbled upon some minor typos.
This commit fixes them.

[Typos] Fixed some minor typos

---

.github/workflows/CI.yml
README.md
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensorCfg.h
src/WeatherSensor.cpp
src/WeatherSensorCfg.h
src/WeatherSensorCfg.h.template

Added LilyGo T3 S3
Added radio chip LR1121

Added LilyGo T3 S3

---

examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.cpp
src/WeatherSensor.cpp

The RF switch configuration for LilyGo T3 S3 LR1121 is required to enable transmitting.
The RF switch of this board isintegrated in the LoRa module.
For schematic, see
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/issues/213
For code example, see
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/examples/T3S3Factory/T3S3Factory.ino#L381

LilyGo T3 S3 LR1121 RF switch and TCXO configuration

---

examples/BresserWeatherSensorDomoticz/BresserWeatherSensorDomoticz.ino
examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
examples/BresserWeatherSensorMQTTCustom/BresserWeatherSensorMQTTCustom.ino
examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino

Added note regarding further sleep current reduction by circuit/radio device dependent GPIO control.

Added weatherSensor.sleep() to all examples with sleep mode

---

examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino

This should probably be SENSOR_TYPE_LIGHTNING like in the other examples.

Fix payload generation for lightning sensor

---

examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
examples/BresserWeatherSensorMQTT/src/mqtt_comm.cpp
examples/BresserWeatherSensorMQTT/src/mqtt_comm.h
examples/BresserWeatherSensorMQTTCustom/BresserWeatherSensorMQTTCustom.ino
examples/BresserWeatherSensorMQTTCustom/src/Lightning.h
examples/BresserWeatherSensorMQTTCustom/src/RainGauge.h
examples/BresserWeatherSensorMQTTCustom/src/mqtt_comm.cpp
examples/BresserWeatherSensorMQTTCustom/src/mqtt_comm.h
examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino
examples/BresserWeatherSensorMQTTWifiMgr/src/mqtt_comm.cpp
examples/BresserWeatherSensorMQTTWifiMgr/src/mqtt_comm.h
src/Lightning.h
src/RainGauge.h

Moved MQTT functions from sketches to mqtt_comm.h/.cpp for easier maintenance.

20250223 refactoring

---

README.md
examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
examples/BresserWeatherSensorMQTT/src/mqtt_comm.cpp
examples/BresserWeatherSensorMQTT/src/mqtt_comm.h
examples/BresserWeatherSensorMQTTCustom/BresserWeatherSensorMQTTCustom.ino
examples/BresserWeatherSensorMQTTCustom/src/WeatherSensor.h
examples/BresserWeatherSensorMQTTCustom/src/mqtt_comm.cpp
examples/BresserWeatherSensorMQTTCustom/src/mqtt_comm.h
examples/BresserWeatherSensorMQTTWifiMgr/BresserWeatherSensorMQTTWifiMgr.ino
examples/BresserWeatherSensorMQTTWifiMgr/src/mqtt_comm.cpp
examples/BresserWeatherSensorMQTTWifiMgr/src/mqtt_comm.h
src/WeatherSensor.h
weather_sensor_receiver_config.yaml

- Added sensor battery status message discovery
- Added sensor signal strength message discovery
- Added weather sensor control/status message discovery

Enhanced MQTT discovery

---

.github/workflows/CI.yml
examples/BresserWeatherSensorMQTT/BresserWeatherSensorMQTT.ino
examples/BresserWeatherSensorMQTT/src/mqtt_comm.cpp

For compatibility with https://github.com/matthias-bs/ESP32-e-Paper-Weather-Display/

Add combined Weather & Soil Sensor data message
